# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f6ede9dfc3f767b65f07e9c9793b885"
name = "countdown-timer"
application_url = "https://highly-digital-mentioned-offline.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ostadstore99.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://highly-digital-mentioned-offline.trycloudflare.com/auth/callback",
  "https://highly-digital-mentioned-offline.trycloudflare.com/auth/shopify/callback",
  "https://highly-digital-mentioned-offline.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
